version: '3.8'

services:
  server:
    build:
      context: ./contestr
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
        required: true
    environment:
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_DATABASE: "${MONGO_DATABASE}"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
    env_file:
      - ./contestr/.env

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "'db.runCommand({ping:1})'" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongo-init-scripts:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:
