services:
  nginx:
    build:
      context: .
      dockerfile: contestr-front/Dockerfile
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "127.0.0.1:10888:80"

  server:
    build:
      context: ./contestr
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
        required: true
    environment:
      APP_MONGODB_URI: "mongodb://mongodb:27017"
      APP_MONGODB_DATABASE: "contestr"
    env_file:
      - ./contestr/.env

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:15432:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ping:1})'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      MONGO_INITDB_DATABASE: "contestr"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongo-init-scripts:/docker-entrypoint-initdb.d

volumes:
  mongodb_data:
