version: '3.8'

services:
  api:
    build:
      context: ./contestr
      dockerfile: deployments/docker/Dockerfile.api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - CONFIG_PATH=/app/configs/config.yaml

  bot:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.bot
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - CONFIG_PATH=/app/configs/config.yaml

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
