version: '3.8'

services:
  server:
    build:
      context: ./contestr
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - ./contestr/.env

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
