// This file is auto-generated by @hey-api/openapi-ts

import { type Options, registerPlayer, getCoreSportList, getCoreTeamsByActivityById, getCoreActivitiesBySportSectionById, postCoreActivityByIdEnroll } from '../sdk.gen';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { RegisterPlayerData, RegisterPlayerError, RegisterPlayerResponse, GetCoreSportListData, GetCoreTeamsByActivityByIdData, GetCoreActivitiesBySportSectionByIdData, PostCoreActivityByIdEnrollData, PostCoreActivityByIdEnrollError, PostCoreActivityByIdEnrollResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const registerPlayerQueryKey = (options: Options<RegisterPlayerData>) => createQueryKey('registerPlayer', options);

/**
 * Регистрирует пользователя
 */
export const registerPlayerOptions = (options: Options<RegisterPlayerData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await registerPlayer({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: registerPlayerQueryKey(options)
    });
};

/**
 * Регистрирует пользователя
 */
export const registerPlayerMutation = (options?: Partial<Options<RegisterPlayerData>>): UseMutationOptions<RegisterPlayerResponse, RegisterPlayerError, Options<RegisterPlayerData>> => {
    const mutationOptions: UseMutationOptions<RegisterPlayerResponse, RegisterPlayerError, Options<RegisterPlayerData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await registerPlayer({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCoreSportListQueryKey = (options?: Options<GetCoreSportListData>) => createQueryKey('getCoreSportList', options);

/**
 * Возвращает список всех существующих видов спорта
 */
export const getCoreSportListOptions = (options?: Options<GetCoreSportListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCoreSportList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCoreSportListQueryKey(options)
    });
};

export const getCoreTeamsByActivityByIdQueryKey = (options: Options<GetCoreTeamsByActivityByIdData>) => createQueryKey('getCoreTeamsByActivityById', options);

/**
 * Получение активности по идентификатору
 */
export const getCoreTeamsByActivityByIdOptions = (options: Options<GetCoreTeamsByActivityByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCoreTeamsByActivityById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCoreTeamsByActivityByIdQueryKey(options)
    });
};

export const getCoreActivitiesBySportSectionByIdQueryKey = (options: Options<GetCoreActivitiesBySportSectionByIdData>) => createQueryKey('getCoreActivitiesBySportSectionById', options);

/**
 * Возвращает список всех активностей по спорту
 */
export const getCoreActivitiesBySportSectionByIdOptions = (options: Options<GetCoreActivitiesBySportSectionByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCoreActivitiesBySportSectionById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCoreActivitiesBySportSectionByIdQueryKey(options)
    });
};

export const postCoreActivityByIdEnrollQueryKey = (options: Options<PostCoreActivityByIdEnrollData>) => createQueryKey('postCoreActivityByIdEnroll', options);

/**
 * Создает команду из одного человека на активность
 */
export const postCoreActivityByIdEnrollOptions = (options: Options<PostCoreActivityByIdEnrollData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postCoreActivityByIdEnroll({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postCoreActivityByIdEnrollQueryKey(options)
    });
};

/**
 * Создает команду из одного человека на активность
 */
export const postCoreActivityByIdEnrollMutation = (options?: Partial<Options<PostCoreActivityByIdEnrollData>>): UseMutationOptions<PostCoreActivityByIdEnrollResponse, PostCoreActivityByIdEnrollError, Options<PostCoreActivityByIdEnrollData>> => {
    const mutationOptions: UseMutationOptions<PostCoreActivityByIdEnrollResponse, PostCoreActivityByIdEnrollError, Options<PostCoreActivityByIdEnrollData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postCoreActivityByIdEnroll({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};