// This file is auto-generated by @hey-api/openapi-ts

import { type Options, registerPlayer, getCorePlayerByTg, getCoreSportList, getCoreTeamsByActivityById, postCoreActivityCreate, postCoreActivityDeleteByById, postCoreActivityUpdateByById, getCoreActivitiesBySportSectionById, getCoreActivityById, postCoreActivityByIdEnroll, postCoreActivityByIdLeave } from '../sdk.gen';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { RegisterPlayerData, RegisterPlayerError, RegisterPlayerResponse, GetCorePlayerByTgData, GetCoreSportListData, GetCoreTeamsByActivityByIdData, PostCoreActivityCreateData, PostCoreActivityCreateError, PostCoreActivityCreateResponse, PostCoreActivityDeleteByByIdData, PostCoreActivityDeleteByByIdError, PostCoreActivityDeleteByByIdResponse, PostCoreActivityUpdateByByIdData, PostCoreActivityUpdateByByIdError, PostCoreActivityUpdateByByIdResponse, GetCoreActivitiesBySportSectionByIdData, GetCoreActivityByIdData, PostCoreActivityByIdEnrollData, PostCoreActivityByIdEnrollError, PostCoreActivityByIdEnrollResponse, PostCoreActivityByIdLeaveData, PostCoreActivityByIdLeaveError } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const registerPlayerQueryKey = (options: Options<RegisterPlayerData>) => createQueryKey('registerPlayer', options);

/**
 * Регистрирует пользователя
 */
export const registerPlayerOptions = (options: Options<RegisterPlayerData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await registerPlayer({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: registerPlayerQueryKey(options)
    });
};

/**
 * Регистрирует пользователя
 */
export const registerPlayerMutation = (options?: Partial<Options<RegisterPlayerData>>): UseMutationOptions<RegisterPlayerResponse, RegisterPlayerError, Options<RegisterPlayerData>> => {
    const mutationOptions: UseMutationOptions<RegisterPlayerResponse, RegisterPlayerError, Options<RegisterPlayerData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await registerPlayer({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCorePlayerByTgQueryKey = (options?: Options<GetCorePlayerByTgData>) => createQueryKey('getCorePlayerByTg', options);

/**
 * Получение пользователя по телеграму
 */
export const getCorePlayerByTgOptions = (options?: Options<GetCorePlayerByTgData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCorePlayerByTg({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCorePlayerByTgQueryKey(options)
    });
};

export const getCoreSportListQueryKey = (options?: Options<GetCoreSportListData>) => createQueryKey('getCoreSportList', options);

/**
 * Возвращает список всех существующих видов спорта
 */
export const getCoreSportListOptions = (options?: Options<GetCoreSportListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCoreSportList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCoreSportListQueryKey(options)
    });
};

export const getCoreTeamsByActivityByIdQueryKey = (options: Options<GetCoreTeamsByActivityByIdData>) => createQueryKey('getCoreTeamsByActivityById', options);

/**
 * Получение активности по идентификатору
 */
export const getCoreTeamsByActivityByIdOptions = (options: Options<GetCoreTeamsByActivityByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCoreTeamsByActivityById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCoreTeamsByActivityByIdQueryKey(options)
    });
};

export const postCoreActivityCreateQueryKey = (options: Options<PostCoreActivityCreateData>) => createQueryKey('postCoreActivityCreate', options);

/**
 * Создает активность
 */
export const postCoreActivityCreateOptions = (options: Options<PostCoreActivityCreateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postCoreActivityCreate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postCoreActivityCreateQueryKey(options)
    });
};

/**
 * Создает активность
 */
export const postCoreActivityCreateMutation = (options?: Partial<Options<PostCoreActivityCreateData>>): UseMutationOptions<PostCoreActivityCreateResponse, PostCoreActivityCreateError, Options<PostCoreActivityCreateData>> => {
    const mutationOptions: UseMutationOptions<PostCoreActivityCreateResponse, PostCoreActivityCreateError, Options<PostCoreActivityCreateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postCoreActivityCreate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postCoreActivityDeleteByByIdQueryKey = (options: Options<PostCoreActivityDeleteByByIdData>) => createQueryKey('postCoreActivityDeleteByById', options);

/**
 * Удаляет активность
 */
export const postCoreActivityDeleteByByIdOptions = (options: Options<PostCoreActivityDeleteByByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postCoreActivityDeleteByById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postCoreActivityDeleteByByIdQueryKey(options)
    });
};

/**
 * Удаляет активность
 */
export const postCoreActivityDeleteByByIdMutation = (options?: Partial<Options<PostCoreActivityDeleteByByIdData>>): UseMutationOptions<PostCoreActivityDeleteByByIdResponse, PostCoreActivityDeleteByByIdError, Options<PostCoreActivityDeleteByByIdData>> => {
    const mutationOptions: UseMutationOptions<PostCoreActivityDeleteByByIdResponse, PostCoreActivityDeleteByByIdError, Options<PostCoreActivityDeleteByByIdData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postCoreActivityDeleteByById({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postCoreActivityUpdateByByIdQueryKey = (options: Options<PostCoreActivityUpdateByByIdData>) => createQueryKey('postCoreActivityUpdateByById', options);

/**
 * Изменяет активность
 */
export const postCoreActivityUpdateByByIdOptions = (options: Options<PostCoreActivityUpdateByByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postCoreActivityUpdateByById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postCoreActivityUpdateByByIdQueryKey(options)
    });
};

/**
 * Изменяет активность
 */
export const postCoreActivityUpdateByByIdMutation = (options?: Partial<Options<PostCoreActivityUpdateByByIdData>>): UseMutationOptions<PostCoreActivityUpdateByByIdResponse, PostCoreActivityUpdateByByIdError, Options<PostCoreActivityUpdateByByIdData>> => {
    const mutationOptions: UseMutationOptions<PostCoreActivityUpdateByByIdResponse, PostCoreActivityUpdateByByIdError, Options<PostCoreActivityUpdateByByIdData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postCoreActivityUpdateByById({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCoreActivitiesBySportSectionByIdQueryKey = (options: Options<GetCoreActivitiesBySportSectionByIdData>) => createQueryKey('getCoreActivitiesBySportSectionById', options);

/**
 * Возвращает список всех активностей по спорту
 */
export const getCoreActivitiesBySportSectionByIdOptions = (options: Options<GetCoreActivitiesBySportSectionByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCoreActivitiesBySportSectionById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCoreActivitiesBySportSectionByIdQueryKey(options)
    });
};

export const getCoreActivityByIdQueryKey = (options: Options<GetCoreActivityByIdData>) => createQueryKey('getCoreActivityById', options);

/**
 * Получение активности по идентификатору
 */
export const getCoreActivityByIdOptions = (options: Options<GetCoreActivityByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getCoreActivityById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getCoreActivityByIdQueryKey(options)
    });
};

export const postCoreActivityByIdEnrollQueryKey = (options: Options<PostCoreActivityByIdEnrollData>) => createQueryKey('postCoreActivityByIdEnroll', options);

/**
 * Создает команду из одного человека на активность
 */
export const postCoreActivityByIdEnrollOptions = (options: Options<PostCoreActivityByIdEnrollData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postCoreActivityByIdEnroll({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postCoreActivityByIdEnrollQueryKey(options)
    });
};

/**
 * Создает команду из одного человека на активность
 */
export const postCoreActivityByIdEnrollMutation = (options?: Partial<Options<PostCoreActivityByIdEnrollData>>): UseMutationOptions<PostCoreActivityByIdEnrollResponse, PostCoreActivityByIdEnrollError, Options<PostCoreActivityByIdEnrollData>> => {
    const mutationOptions: UseMutationOptions<PostCoreActivityByIdEnrollResponse, PostCoreActivityByIdEnrollError, Options<PostCoreActivityByIdEnrollData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postCoreActivityByIdEnroll({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postCoreActivityByIdLeaveQueryKey = (options: Options<PostCoreActivityByIdLeaveData>) => createQueryKey('postCoreActivityByIdLeave', options);

/**
 * Отписывает человека из активности, удаляет из команды
 */
export const postCoreActivityByIdLeaveOptions = (options: Options<PostCoreActivityByIdLeaveData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await postCoreActivityByIdLeave({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: postCoreActivityByIdLeaveQueryKey(options)
    });
};

/**
 * Отписывает человека из активности, удаляет из команды
 */
export const postCoreActivityByIdLeaveMutation = (options?: Partial<Options<PostCoreActivityByIdLeaveData>>): UseMutationOptions<unknown, PostCoreActivityByIdLeaveError, Options<PostCoreActivityByIdLeaveData>> => {
    const mutationOptions: UseMutationOptions<unknown, PostCoreActivityByIdLeaveError, Options<PostCoreActivityByIdLeaveData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await postCoreActivityByIdLeave({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};