// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getRegattaContestStandings, getContest, getContest2, getHello } from '../sdk.gen';
import { queryOptions } from '@tanstack/react-query';
import type { GetRegattaContestStandingsData, GetContestData, GetContest2Data, GetHelloData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getRegattaContestStandingsQueryKey = (options?: Options<GetRegattaContestStandingsData>) => createQueryKey('getRegattaContestStandings', options);

export const getRegattaContestStandingsOptions = (options?: Options<GetRegattaContestStandingsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getRegattaContestStandings({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getRegattaContestStandingsQueryKey(options)
    });
};

export const getContestQueryKey = (options?: Options<GetContestData>) => createQueryKey('getContest', options);

export const getContestOptions = (options?: Options<GetContestData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getContest({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getContestQueryKey(options)
    });
};

export const getContest2QueryKey = (options?: Options<GetContest2Data>) => createQueryKey('getContest2', options);

export const getContest2Options = (options?: Options<GetContest2Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getContest2({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getContest2QueryKey(options)
    });
};

export const getHelloQueryKey = (options?: Options<GetHelloData>) => createQueryKey('getHello', options);

export const getHelloOptions = (options?: Options<GetHelloData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getHello({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getHelloQueryKey(options)
    });
};