// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetRegattaContestStandingsData, GetRegattaContestStandingsResponses, GetContestData, GetContestResponses, GetContest2Data, GetContest2Responses, GetHelloData, GetHelloResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getRegattaContestStandings = <ThrowOnError extends boolean = false>(options?: Options<GetRegattaContestStandingsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRegattaContestStandingsResponses, unknown, ThrowOnError>({
        url: '/regatta/contests/{contest_id}',
        ...options
    });
};

export const getContest = <ThrowOnError extends boolean = false>(options?: Options<GetContestData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetContestResponses, unknown, ThrowOnError>({
        url: '/plugins/whoami/whoami.php',
        ...options
    });
};

export const getContest2 = <ThrowOnError extends boolean = false>(options?: Options<GetContest2Data, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetContest2Responses, unknown, ThrowOnError>({
        url: '/cfcontest/{contest_id}',
        ...options
    });
};

export const getHello = <ThrowOnError extends boolean = false>(options?: Options<GetHelloData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetHelloResponses, unknown, ThrowOnError>({
        url: '/hello',
        ...options
    });
};