// This file is auto-generated by @hey-api/openapi-ts

export type RegattaContestRow = {
    /**
     * Имя и фамилия студента одной строкой
     */
    display_name: string;
    /**
     * Номер команды
     */
    team_number: number;
    /**
     * Общий счёт в баллах
     */
    total_score: number;
    /**
     * Количество решенных задач
     */
    solved_problems: number;
    /**
     * Результаты по задачам в формате "идентификатор задачи -> баллы", либо <0 за неудачную попытку
     */
    problem_results: Array<ProblemResult>;
    /**
     * Идентификатор студента
     */
    user_id: number;
};

/**
 * Результаты по задаче, c буквой задачи, счётом и временем последней попытки. Если score < 0, то попытка неудачна. Время последней посылки отправляется только для удачных посылок
 */
export type ProblemResult = {
    problem_code: string;
    score: number;
    last_submission_time?: number;
};

export type Contest = {
    id: string;
    name: string;
};

export type Hello = {
    message: string;
    timestamp?: string;
};

export type _Error = {
    message: string;
};

export type GetRegattaContestStandingsData = {
    body?: never;
    path?: {
        contest_id?: number;
    };
    query?: never;
    url: '/regatta/contests/{contest_id}';
};

export type GetRegattaContestStandingsResponses = {
    /**
     * Список студентов с результатами контеста
     */
    200: {
        /**
         * Название контеста
         */
        contest_name: string;
        /**
         * Идентификатор контеста
         */
        contest_id: number;
        /**
         * Время начала последнего тура
         */
        current_tour_start_time: number;
        /**
         * Длительность последнего тура в минутах
         */
        current_tour_duration: number;
        rows: Array<RegattaContestRow>;
    };
};

export type GetRegattaContestStandingsResponse = GetRegattaContestStandingsResponses[keyof GetRegattaContestStandingsResponses];

export type GetContestData = {
    body?: never;
    path?: {
        contest_id?: number;
    };
    query?: never;
    url: '/cfcontest/{contest_id}';
};

export type GetContestResponses = {
    /**
     * Информацию о результатах контеста
     */
    200: Contest;
};

export type GetContestResponse = GetContestResponses[keyof GetContestResponses];

export type GetHelloData = {
    body?: never;
    path?: never;
    query?: {
        name?: string;
    };
    url: '/hello';
};

export type GetHelloResponses = {
    /**
     * hello handle
     */
    200: Hello;
};

export type GetHelloResponse = GetHelloResponses[keyof GetHelloResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};