openapi: 3.0.0
info:
  title: Contests API
  description: Ручки для получения данных о контестах
  version: 1.0.0
paths:
  /contest/{contest_id}:
    get:
      operationId: getContest
      parameters:
        - name: contest_id
          in: path
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/GetContestResponse'
  /hello:
    get:
      operationId: getHello
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        200:
          description: hello handle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
components:
  responses:
    GetContestResponse:
      description: Информацию о результатах контеста
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Contest'

    ErrorResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Contest:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Hello:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
