openapi: 3.0.0
info:
  title: Contests API
  description: Ручки для получения данных о контестах
  version: 1.0.0
paths:
  /regatta/contests/{contest_id}:
    get:
      operationId: getRegattaContestStandings
      parameters:
        - name: contest_id
          in: path
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/RegattaContestStandings'

  # TODO
  /cfcontest/{contest_id}:
    get:
      operationId: getContest
      parameters:
        - name: contest_id
          in: path
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/GetContestResponse'
  /hello:
    get:
      operationId: getHello
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        200:
          description: hello handle
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
components:
  responses:
    RegattaContestStandings:
      description: Список студентов с результатами контеста
      content:
        application/json:
          schema:
            type: object
            required:
              - contest_name
              - contest_id
              - current_tour_start_time
              - current_tour_duration
              - rows
            properties:
              contest_name:
                type: string
                description: Название контеста
              contest_id:
                type: integer
                description: Идентификатор контеста
              current_tour_start_time:
                type: integer
                description: Время начала последнего тура (Unix timestamp в секундах)
              current_tour_duration:
                type: integer
                description: Длительность последнего тура в минутах
              rows:
                type: array
                items:
                  $ref: '#/components/schemas/RegattaContestRow'

    GetContestResponse:
      description: Информацию о результатах контеста
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Contest'

    ErrorResponse:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    RegattaContestRow:
      type: object
      required:
        - display_name
        - team_number
        - total_score
        - solved_problems
        - problem_results
        - user_id
      properties:
        display_name:
          type: string
          description: Имя и фамилия студента одной строкой
          example: "Иван Иванов"
        team_number:
          type: integer
          description: Номер команды
        total_score:
          type: number
          description: Общий счёт в баллах
          example: 350
        solved_problems:
          type: integer
          description: Количество решенных задач
          example: 7
        problem_results:
          type: array
          description: Результаты по задачам в формате "идентификатор задачи -> баллы", либо <0 за неудачную попытку
          items:
            $ref: '#/components/schemas/ProblemResult'
        user_id:
          type: string
          description: Идентификатор студента
    ProblemResult:
      type: object
      required:
        - problem_code
        - score
      description: Результаты по задаче, c буквой задачи, счётом и временем последней попытки. Если score < 0, то попытка неудачна. Время последней посылки отправляется только для удачных посылок
      properties:
        problem_code:
          type: string
        score:
          type: integer
        last_submission_time:
          description: Время последней посылки в секундах с начала контеста
          type: integer
    Contest:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Hello:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string

