// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { RegisterPlayerData, RegisterPlayerResponses, RegisterPlayerErrors, GetCoreSportListData, GetCoreSportListResponses, GetCoreTeamsByActivityByIdData, GetCoreTeamsByActivityByIdResponses, GetCoreTeamsByActivityByIdErrors, GetCoreActivitiesBySportSectionByIdData, GetCoreActivitiesBySportSectionByIdResponses, GetCoreActivitiesBySportSectionByIdErrors, PostCoreActivityByIdEnrollData, PostCoreActivityByIdEnrollResponses, PostCoreActivityByIdEnrollErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Регистрирует пользователя
 */
export const registerPlayer = <ThrowOnError extends boolean = false>(options: Options<RegisterPlayerData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterPlayerResponses, RegisterPlayerErrors, ThrowOnError>({
        url: '/core/player/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Возвращает список всех существующих видов спорта
 */
export const getCoreSportList = <ThrowOnError extends boolean = false>(options?: Options<GetCoreSportListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCoreSportListResponses, unknown, ThrowOnError>({
        url: '/core/sport/list',
        ...options
    });
};

/**
 * Получение активности по идентификатору
 */
export const getCoreTeamsByActivityById = <ThrowOnError extends boolean = false>(options: Options<GetCoreTeamsByActivityByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCoreTeamsByActivityByIdResponses, GetCoreTeamsByActivityByIdErrors, ThrowOnError>({
        url: '/core/teams/by_activity/{id}',
        ...options
    });
};

/**
 * Возвращает список всех активностей по спорту
 */
export const getCoreActivitiesBySportSectionById = <ThrowOnError extends boolean = false>(options: Options<GetCoreActivitiesBySportSectionByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCoreActivitiesBySportSectionByIdResponses, GetCoreActivitiesBySportSectionByIdErrors, ThrowOnError>({
        url: '/core/activities/by_sport_section/{id}',
        ...options
    });
};

/**
 * Создает команду из одного человека на активность
 */
export const postCoreActivityByIdEnroll = <ThrowOnError extends boolean = false>(options: Options<PostCoreActivityByIdEnrollData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCoreActivityByIdEnrollResponses, PostCoreActivityByIdEnrollErrors, ThrowOnError>({
        url: '/core/activity/{id}/enroll',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};