// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { RegisterPlayerData, RegisterPlayerResponses, RegisterPlayerErrors, GetCorePlayerByTgData, GetCorePlayerByTgResponses, GetCorePlayerByTgErrors, GetCoreSportListData, GetCoreSportListResponses, GetCoreTeamsByActivityByIdData, GetCoreTeamsByActivityByIdResponses, GetCoreTeamsByActivityByIdErrors, PostCoreActivityCreateData, PostCoreActivityCreateResponses, PostCoreActivityCreateErrors, PostCoreActivityDeleteByByIdData, PostCoreActivityDeleteByByIdResponses, PostCoreActivityDeleteByByIdErrors, PostCoreActivityUpdateByByIdData, PostCoreActivityUpdateByByIdResponses, PostCoreActivityUpdateByByIdErrors, GetCoreActivitiesBySportSectionByIdData, GetCoreActivitiesBySportSectionByIdResponses, GetCoreActivitiesBySportSectionByIdErrors, GetCoreActivityByIdData, GetCoreActivityByIdResponses, GetCoreActivityByIdErrors, PostCoreActivityByIdEnrollData, PostCoreActivityByIdEnrollResponses, PostCoreActivityByIdEnrollErrors, PostCoreActivityByIdLeaveData, PostCoreActivityByIdLeaveResponses, PostCoreActivityByIdLeaveErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Регистрирует пользователя
 */
export const registerPlayer = <ThrowOnError extends boolean = false>(options: Options<RegisterPlayerData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterPlayerResponses, RegisterPlayerErrors, ThrowOnError>({
        url: '/core/player/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Получение пользователя по телеграму
 */
export const getCorePlayerByTg = <ThrowOnError extends boolean = false>(options?: Options<GetCorePlayerByTgData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCorePlayerByTgResponses, GetCorePlayerByTgErrors, ThrowOnError>({
        url: '/core/player/by_tg',
        ...options
    });
};

/**
 * Возвращает список всех существующих видов спорта
 */
export const getCoreSportList = <ThrowOnError extends boolean = false>(options?: Options<GetCoreSportListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCoreSportListResponses, unknown, ThrowOnError>({
        url: '/core/sport/list',
        ...options
    });
};

/**
 * Получение активности по идентификатору
 */
export const getCoreTeamsByActivityById = <ThrowOnError extends boolean = false>(options: Options<GetCoreTeamsByActivityByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCoreTeamsByActivityByIdResponses, GetCoreTeamsByActivityByIdErrors, ThrowOnError>({
        url: '/core/teams/by_activity/{id}',
        ...options
    });
};

/**
 * Создает активность
 */
export const postCoreActivityCreate = <ThrowOnError extends boolean = false>(options: Options<PostCoreActivityCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCoreActivityCreateResponses, PostCoreActivityCreateErrors, ThrowOnError>({
        url: '/core/activity/create',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Удаляет активность
 */
export const postCoreActivityDeleteByById = <ThrowOnError extends boolean = false>(options: Options<PostCoreActivityDeleteByByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCoreActivityDeleteByByIdResponses, PostCoreActivityDeleteByByIdErrors, ThrowOnError>({
        url: '/core/activity/delete_by/{id}',
        ...options
    });
};

/**
 * Изменяет активность
 */
export const postCoreActivityUpdateByById = <ThrowOnError extends boolean = false>(options: Options<PostCoreActivityUpdateByByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCoreActivityUpdateByByIdResponses, PostCoreActivityUpdateByByIdErrors, ThrowOnError>({
        url: '/core/activity/update_by/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Возвращает список всех активностей по спорту
 */
export const getCoreActivitiesBySportSectionById = <ThrowOnError extends boolean = false>(options: Options<GetCoreActivitiesBySportSectionByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCoreActivitiesBySportSectionByIdResponses, GetCoreActivitiesBySportSectionByIdErrors, ThrowOnError>({
        url: '/core/activities/by_sport_section/{id}',
        ...options
    });
};

/**
 * Получение активности по идентификатору
 */
export const getCoreActivityById = <ThrowOnError extends boolean = false>(options: Options<GetCoreActivityByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCoreActivityByIdResponses, GetCoreActivityByIdErrors, ThrowOnError>({
        url: '/core/activity/{id}',
        ...options
    });
};

/**
 * Создает команду из одного человека на активность
 */
export const postCoreActivityByIdEnroll = <ThrowOnError extends boolean = false>(options: Options<PostCoreActivityByIdEnrollData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCoreActivityByIdEnrollResponses, PostCoreActivityByIdEnrollErrors, ThrowOnError>({
        url: '/core/activity/{id}/enroll',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Отписывает человека из активности, удаляет из команды
 */
export const postCoreActivityByIdLeave = <ThrowOnError extends boolean = false>(options: Options<PostCoreActivityByIdLeaveData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCoreActivityByIdLeaveResponses, PostCoreActivityByIdLeaveErrors, ThrowOnError>({
        url: '/core/activity/{id}/leave',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};