// This file is auto-generated by @hey-api/openapi-ts

/**
 * Структура описывающая пользователя
 */
export type Player = {
    coreId: number;
    tgId: number;
};

export type PlayerList = Array<Player>;

export type SportSection = {
    id: number;
    name: string;
    ru_name: string;
};

export type SportSectionList = Array<SportSection>;

/**
 * Команда с игроками
 */
export type Team = {
    id: number;
    name: string;
    captain: Player;
    members: PlayerList;
};

export type TeamList = Array<Team>;

export type Activity = {
    /**
     * Идентификатор активности
     */
    id: number;
    title: string;
    description?: string;
    creator: Player;
};

export type RegisterPlayerRequest = {
    tg_username: string;
    name: string;
    tg_id: number;
};

export type ActivityEnrollPlayerRequest = {
    tgId?: number;
};

export type RegisterPlayerData = {
    body: RegisterPlayerRequest;
    path?: never;
    query?: never;
    url: '/core/player/register';
};

export type RegisterPlayerErrors = {
    500: {
        message: string;
    };
};

export type RegisterPlayerError = RegisterPlayerErrors[keyof RegisterPlayerErrors];

export type RegisterPlayerResponses = {
    /**
     * Информация о регистрации пользователя
     */
    200: {
        /**
         * Core-идентификатор
         */
        id: number;
    };
    /**
     * Информация о регистрации пользователя
     */
    201: {
        /**
         * Core-идентификатор
         */
        id: number;
    };
};

export type RegisterPlayerResponse = RegisterPlayerResponses[keyof RegisterPlayerResponses];

export type GetCoreSportListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/sport/list';
};

export type GetCoreSportListResponses = {
    /**
     * Массив, в котором содержатся названия всех существующих видов спорта
     */
    200: {
        sports_sections: SportSectionList;
    };
};

export type GetCoreSportListResponse = GetCoreSportListResponses[keyof GetCoreSportListResponses];

export type GetCoreTeamsByActivityByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/core/teams/by_activity/{id}';
};

export type GetCoreTeamsByActivityByIdErrors = {
    400: {
        message: string;
    };
};

export type GetCoreTeamsByActivityByIdError = GetCoreTeamsByActivityByIdErrors[keyof GetCoreTeamsByActivityByIdErrors];

export type GetCoreTeamsByActivityByIdResponses = {
    /**
     * Список команд, записанных на активность
     */
    200: {
        teams: TeamList;
    };
};

export type GetCoreTeamsByActivityByIdResponse = GetCoreTeamsByActivityByIdResponses[keyof GetCoreTeamsByActivityByIdResponses];

export type GetCoreActivitiesBySportSectionByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/core/activities/by_sport_section/{id}';
};

export type GetCoreActivitiesBySportSectionByIdErrors = {
    400: {
        message: string;
    };
};

export type GetCoreActivitiesBySportSectionByIdError = GetCoreActivitiesBySportSectionByIdErrors[keyof GetCoreActivitiesBySportSectionByIdErrors];

export type GetCoreActivitiesBySportSectionByIdResponses = {
    /**
     * Список активностей
     */
    200: {
        activities: Array<Activity>;
    };
};

export type GetCoreActivitiesBySportSectionByIdResponse = GetCoreActivitiesBySportSectionByIdResponses[keyof GetCoreActivitiesBySportSectionByIdResponses];

export type PostCoreActivityByIdEnrollData = {
    body: ActivityEnrollPlayerRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/core/activity/{id}/enroll';
};

export type PostCoreActivityByIdEnrollErrors = {
    400: {
        message: string;
    };
};

export type PostCoreActivityByIdEnrollError = PostCoreActivityByIdEnrollErrors[keyof PostCoreActivityByIdEnrollErrors];

export type PostCoreActivityByIdEnrollResponses = {
    /**
     * Созданная команда
     */
    200: {
        team: Team;
    };
};

export type PostCoreActivityByIdEnrollResponse = PostCoreActivityByIdEnrollResponses[keyof PostCoreActivityByIdEnrollResponses];

export type ClientOptions = {
    baseUrl: `${string}://match-integration` | (string & {});
};