// This file is auto-generated by @hey-api/openapi-ts

/**
 * Структура описывающая пользователя
 */
export type Player = {
    core_id: number;
    name: string;
    tg_id: number;
    tg_username: string;
};

export type PlayerList = Array<Player>;

export type SportSection = {
    id: number;
    name: string;
    ru_name: string;
};

export type SportSectionList = Array<SportSection>;

/**
 * Команда с игроками
 */
export type Team = {
    id: number;
    name: string;
    captain: Player;
    members: PlayerList;
};

export type TeamList = Array<Team>;

export type Activity = {
    /**
     * Идентификатор активности
     */
    id: number;
    title: string;
    description?: string;
    creator: Player;
    /**
     * Идентификатор спортивной секции
     */
    sport_section_id: number;
    enroll_deadline?: unknown;
};

export type RegisterPlayerRequest = {
    tg_username: string;
    name: string;
    tg_id: number;
};

export type CreateActivityRequest = {
    /**
     * Название активности
     */
    title: string;
    /**
     * Описание активности
     */
    description?: string;
    sport_section_id: number;
    /**
     * Идентификатор создателя активности в ядре
     */
    creator_id: number;
    /**
     * Время
     */
    enroll_deadline?: string;
};

export type UpdateActivityRequest = {
    /**
     * Название активности
     */
    title?: string;
    /**
     * Описание активности
     */
    description?: string;
    /**
     * Идентификатор создателя активности в ядре
     */
    creator_id?: number;
    enroll_deadline?: string;
};

export type ActivityEnrollPlayerRequest = {
    id: number;
};

export type ActivityLeavePlayerRequest = {
    id: number;
};

export type PrivilegeToken = string;

export type RegisterPlayerData = {
    body: RegisterPlayerRequest;
    path?: never;
    query?: never;
    url: '/core/player/register';
};

export type RegisterPlayerErrors = {
    500: {
        message: string;
    };
};

export type RegisterPlayerError = RegisterPlayerErrors[keyof RegisterPlayerErrors];

export type RegisterPlayerResponses = {
    /**
     * Информация о регистрации пользователя
     */
    200: {
        /**
         * Идентификатор в ядре
         */
        id: number;
    };
    /**
     * Информация о регистрации пользователя
     */
    201: {
        /**
         * Идентификатор в ядре
         */
        id: number;
    };
};

export type RegisterPlayerResponse = RegisterPlayerResponses[keyof RegisterPlayerResponses];

export type GetCorePlayerByTgData = {
    body?: never;
    path?: never;
    query?: {
        tg_id?: number;
        tg_username?: string;
    };
    url: '/core/player/by_tg';
};

export type GetCorePlayerByTgErrors = {
    400: {
        message: string;
    };
};

export type GetCorePlayerByTgError = GetCorePlayerByTgErrors[keyof GetCorePlayerByTgErrors];

export type GetCorePlayerByTgResponses = {
    /**
     * Информация о пользователе
     */
    200: {
        player: Player;
    };
};

export type GetCorePlayerByTgResponse = GetCorePlayerByTgResponses[keyof GetCorePlayerByTgResponses];

export type GetCoreSportListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/core/sport/list';
};

export type GetCoreSportListResponses = {
    /**
     * Массив, в котором содержатся названия всех существующих видов спорта
     */
    200: {
        sports_sections: SportSectionList;
    };
};

export type GetCoreSportListResponse = GetCoreSportListResponses[keyof GetCoreSportListResponses];

export type GetCoreTeamsByActivityByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/core/teams/by_activity/{id}';
};

export type GetCoreTeamsByActivityByIdErrors = {
    400: {
        message: string;
    };
};

export type GetCoreTeamsByActivityByIdError = GetCoreTeamsByActivityByIdErrors[keyof GetCoreTeamsByActivityByIdErrors];

export type GetCoreTeamsByActivityByIdResponses = {
    /**
     * Список команд, записанных на активность
     */
    200: {
        teams: TeamList;
    };
};

export type GetCoreTeamsByActivityByIdResponse = GetCoreTeamsByActivityByIdResponses[keyof GetCoreTeamsByActivityByIdResponses];

export type PostCoreActivityCreateData = {
    body: CreateActivityRequest;
    headers: {
        'Privilege-Token': string;
    };
    path?: never;
    query?: never;
    url: '/core/activity/create';
};

export type PostCoreActivityCreateErrors = {
    400: {
        message: string;
    };
};

export type PostCoreActivityCreateError = PostCoreActivityCreateErrors[keyof PostCoreActivityCreateErrors];

export type PostCoreActivityCreateResponses = {
    /**
     * Информация об активности
     */
    200: {
        activity: Activity;
    };
};

export type PostCoreActivityCreateResponse = PostCoreActivityCreateResponses[keyof PostCoreActivityCreateResponses];

export type PostCoreActivityDeleteByByIdData = {
    body?: never;
    headers: {
        'Privilege-Token': string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/core/activity/delete_by/{id}';
};

export type PostCoreActivityDeleteByByIdErrors = {
    400: {
        message: string;
    };
};

export type PostCoreActivityDeleteByByIdError = PostCoreActivityDeleteByByIdErrors[keyof PostCoreActivityDeleteByByIdErrors];

export type PostCoreActivityDeleteByByIdResponses = {
    /**
     * Информация об активности
     */
    200: {
        activity: Activity;
    };
};

export type PostCoreActivityDeleteByByIdResponse = PostCoreActivityDeleteByByIdResponses[keyof PostCoreActivityDeleteByByIdResponses];

export type PostCoreActivityUpdateByByIdData = {
    body: UpdateActivityRequest;
    headers: {
        'Privilege-Token': string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/core/activity/update_by/{id}';
};

export type PostCoreActivityUpdateByByIdErrors = {
    400: {
        message: string;
    };
};

export type PostCoreActivityUpdateByByIdError = PostCoreActivityUpdateByByIdErrors[keyof PostCoreActivityUpdateByByIdErrors];

export type PostCoreActivityUpdateByByIdResponses = {
    /**
     * Информация об активности
     */
    200: {
        activity: Activity;
    };
};

export type PostCoreActivityUpdateByByIdResponse = PostCoreActivityUpdateByByIdResponses[keyof PostCoreActivityUpdateByByIdResponses];

export type GetCoreActivitiesBySportSectionByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/core/activities/by_sport_section/{id}';
};

export type GetCoreActivitiesBySportSectionByIdErrors = {
    400: {
        message: string;
    };
};

export type GetCoreActivitiesBySportSectionByIdError = GetCoreActivitiesBySportSectionByIdErrors[keyof GetCoreActivitiesBySportSectionByIdErrors];

export type GetCoreActivitiesBySportSectionByIdResponses = {
    /**
     * Список активностей
     */
    200: {
        activities: Array<Activity>;
    };
};

export type GetCoreActivitiesBySportSectionByIdResponse = GetCoreActivitiesBySportSectionByIdResponses[keyof GetCoreActivitiesBySportSectionByIdResponses];

export type GetCoreActivityByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/core/activity/{id}';
};

export type GetCoreActivityByIdErrors = {
    404: {
        message: string;
    };
};

export type GetCoreActivityByIdError = GetCoreActivityByIdErrors[keyof GetCoreActivityByIdErrors];

export type GetCoreActivityByIdResponses = {
    /**
     * Информация об активности
     */
    200: {
        activity: Activity;
    };
};

export type GetCoreActivityByIdResponse = GetCoreActivityByIdResponses[keyof GetCoreActivityByIdResponses];

export type PostCoreActivityByIdEnrollData = {
    body: ActivityEnrollPlayerRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/core/activity/{id}/enroll';
};

export type PostCoreActivityByIdEnrollErrors = {
    400: {
        message: string;
    };
    403: {
        message: string;
    };
    409: {
        message: string;
    };
};

export type PostCoreActivityByIdEnrollError = PostCoreActivityByIdEnrollErrors[keyof PostCoreActivityByIdEnrollErrors];

export type PostCoreActivityByIdEnrollResponses = {
    /**
     * Созданная команда
     */
    200: {
        team: Team;
    };
};

export type PostCoreActivityByIdEnrollResponse = PostCoreActivityByIdEnrollResponses[keyof PostCoreActivityByIdEnrollResponses];

export type PostCoreActivityByIdLeaveData = {
    body: ActivityLeavePlayerRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/core/activity/{id}/leave';
};

export type PostCoreActivityByIdLeaveErrors = {
    404: {
        message: string;
    };
};

export type PostCoreActivityByIdLeaveError = PostCoreActivityByIdLeaveErrors[keyof PostCoreActivityByIdLeaveErrors];

export type PostCoreActivityByIdLeaveResponses = {
    /**
     * Игрок успешно удалён из активности
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://match-integration` | (string & {});
};
