app:
  name: "contestr"
  version: "1.0.0"

http:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

mongodb:
  uri: "mongodb://localhost:27017"
  database: "contestr"
  max_pool_size: 100
  min_pool_size: 10
  tour_collection: "tours"

telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  admins_tg_id:
    - 447498304 # khet

codeforces:
  api_key: "YOUR_CODEFORCES_API_KEY"
  api_secret: "YOUR_CODEFORCES_API_SECRET"

ejudge:
  xml_url: https://ejudge.lksh.ru/ejudge-external
  request_timeout: 10s

contest_sync:
  interval: 15s

timetable_sync:
  interval: 1s

admin:
  jwt_secret: ""
  username: ""
  password: ""
  jwt_ttl: 24h

object_storage:
  endpoint: "https://storage.yandexcloud.net"
  region: "ru-central1"
  bucket: "contestr-statements"
  access_key_id: ""
  secret_access_key: ""
  public_base_url: "https://storage.yandexcloud.net/contestr-statements"
