app:
  name: "contestr"
  version: "1.0.0"

http:
  port: "8080"
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

mongodb:
  uri: "mongodb://localhost:27017"
  database: "codeforces_service"
  max_pool_size: 100
  min_pool_size: 10

telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"

codeforces:
  api_key: "YOUR_CODEFORCES_API_KEY"
  api_secret: "YOUR_CODEFORCES_API_SECRET"
