app:
  name: "contestr"
  version: "1.0.0"

http:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

mongodb:
  uri: "mongodb://localhost:27017"
  database: "codeforces_service"
  max_pool_size: 100
  min_pool_size: 10

telegram:
  token: "YOUR_TELEGRAM_BOT_TOKEN"
  admins_tg_id:
    - 447498304 # khet

codeforces:
  api_key: "YOUR_CODEFORCES_API_KEY"
  api_secret: "YOUR_CODEFORCES_API_SECRET"

ejudge:
  xml_url: https://ejudge.lksh.ru/ejudge-external
  request_timeout: 10s
